// This file will be generated by FlutterFire CLI.
// Run: flutterfire configure
//
// For now, this is a placeholder. After running flutterfire configure,
// this file will be replaced with the actual Firebase configuration.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCM8ksLW4E4shk2TBrh1KV_oLo4JEoKe1U',
    appId: '1:865183756987:android:5670d986449eb632636f9e',
    messagingSenderId: '865183756987',
    projectId: 'flutter-firebase-4b3b1',
    storageBucket: 'flutter-firebase-4b3b1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmwh_NnBzpQORE4ciGV4kvMFFKz4thUdA',
    appId: '1:865183756987:ios:29f20de8eed2a342636f9e',
    messagingSenderId: '865183756987',
    projectId: 'flutter-firebase-4b3b1',
    storageBucket: 'flutter-firebase-4b3b1.firebasestorage.app',
    iosBundleId: 'com.manishsoft.flutterNotification',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuSyvYlv7JxY1EP9o5mGDMyQqVUzfl0v4',
    appId: '1:865183756987:web:9ed0cc1e4cfca1cc636f9e',
    messagingSenderId: '865183756987',
    projectId: 'flutter-firebase-4b3b1',
    authDomain: 'flutter-firebase-4b3b1.firebaseapp.com',
    storageBucket: 'flutter-firebase-4b3b1.firebasestorage.app',
    measurementId: 'G-4F4FR01DPE',
  );

}